- name: Converge
  hosts: all
  gather_facts: false
  tasks:

    - name: Setup
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'distribution'

    - name: Include AnwarYagoub.haproxy role
      ansible.builtin.include_role:
        name: AnwarYagoub.haproxy
