---

- name: Install required packages on Debian based systems
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
    install_recommends: false
    update_cache: true
    state: present

- name: Install HAProxy
  block:
    - name: Install HAProxy | Add HAProxy repository
      ansible.builtin.apt_repository:
        repo: "ppa:vbernat/haproxy-{{ haproxy_version }}"
        state: present
    - name: Install HAProxy | Install packages
      ansible.builtin.apt:
        name: "haproxy={{ haproxy_version }}.*"
        update_cache: true
        state: present

- name: Start & enable HAProxy service
  ansible.builtin.service:
    name: haproxy.service
    state: started
    enabled: true
